# Generated by Django 4.0.5 on 2022-06-30 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('price_usd', models.PositiveIntegerField(verbose_name='цена, USD')),
                ('is_in_stock', models.BooleanField(verbose_name='есть в наличии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='BaseProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m', verbose_name='фото')),
                ('is_title', models.BooleanField(verbose_name='является главной')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.baseproduct')),
                ('datasheet', models.FileField(upload_to='datasheets', verbose_name='документация')),
                ('default_lead_time_weeks', models.PositiveSmallIntegerField(verbose_name='стандартное время отгрузки, недель')),
            ],
            options={
                'verbose_name': 'плата',
                'verbose_name_plural': 'платы',
            },
            bases=('website.baseproduct',),
        ),
        migrations.CreateModel(
            name='BoardPhoto',
            fields=[
                ('baseproductphoto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.baseproductphoto')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.board', verbose_name='плата')),
            ],
            bases=('website.baseproductphoto',),
        ),
    ]
