# Generated by Django 4.0.5 on 2022-06-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_default_lead_time_weeks_board_lead_time_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата посещения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AlterModelOptions(
            name='boardphoto',
            options={'verbose_name': 'фото платы', 'verbose_name_plural': 'фото плат'},
        ),
        migrations.AlterField(
            model_name='board',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='datasheets', verbose_name='документация'),
        ),
    ]
