from django.core.mail import send_mail

from amungo.settings import EMAIL_HOST_USER
from .config import EMAIL_RECEIVERS_LIST, EMAIL_SUBJECT
from .exceptions import SendMessageError


def send_visitor_message(*, sender_name: str, sender_email: str, text: str) -> None:
    email_message = f'New message from: {sender_name} <{sender_email}>:\n\n'\
                    f'{text}\n\n\n'\
                    f'This is an autogenerated message. Reply directly to {sender_email}'
    try:
        send_mail(
            EMAIL_SUBJECT,
            email_message,
            EMAIL_HOST_USER,
            EMAIL_RECEIVERS_LIST,
            fail_silently=False
        )
    except Exception:
        raise SendMessageError('Error during message sending')
